version: '3'
    
services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASS: $MYSQL_PASS
  web:
    build: .
    command: sh -c 'cd /web ; ./wait-for db:3306 -- ./startserver.sh'
    ports:
      - "80:8888"
    depends_on:
      - db
    environment:
      DBHOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASS: $MYSQL_PASS
      adfs_client_id: $adfs_client_id
      adfs_sharedsecret: $adfs_sharedsecret
      adfs_oauth_authorize_url: $adfs_oauth_authorize_url
      adfs_oauth_access_token_url: $adfs_oauth_access_token_url
      adfs_keys_url: $adfs_keys_url
      adfs_redirect_uri: $adfs_redirect_uri
      adfs_logout_uri: $adfs_logout_uri
      
volumes:
  dbdata: {}
